---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.815ee4fa-628a-4e61-8af5-e2e7409c9cf5

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.1c6a9c85-f79c-4f68-bd91-743287bdb5d2.Boolean.Property
        operator: ne
        operands:
            - "false"
