---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.79b6640b-a080-4c2c-8b3b-2ae17f91f1f9

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.ec8edac5-5c1d-4787-a92d-402b6a1f340c.Boolean.Property
        operator: ne
        operands:
            - "false"
