---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.60781605-fe3a-46a2-8d72-66600669bc99

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.6c106e7e-5283-4376-ace6-464725eb914b.Boolean.Property
        operator: ne
        operands:
            - "false"
