---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.28b709f4-b99a-4639-afd8-6612b49bb8c4

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.acb6c7d3-1351-4f82-90c4-2f97d422c8b4.Boolean.Property
        operator: ne
        operands:
            - "false"
