---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.21b96a8f-0923-4bec-bb95-8e046f955b8f

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.0fa2e704-9cdb-414a-9b81-d47c5dcae232.Boolean.Property
        operator: ne
        operands:
            - "false"
