---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.d30bab18-fcb4-4e12-8c93-685f71ab7c16

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.6adf2984-55a3-4c27-a438-6546a95055eb.Boolean.Property
        operator: ne
        operands:
            - "false"
