---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.39c07782-3954-4e0f-9eba-63e169e31d8e

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.11fe61f0-1718-42b2-9b89-f561ea4e90cc.Boolean.Property
        operator: ne
        operands:
            - "false"
