---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.53c9caa1-ea88-41b1-abab-9f62c020c1d1

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.48381b58-880b-41db-ad14-8ec94e530dfc.Boolean.Property
        operator: ne
        operands:
            - "false"
