---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.dc49adce-1b9d-482e-a0c4-e95b74e92c73

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.eabff1ff-ac39-4727-b77d-d68703a72749.Boolean.Property
        operator: ne
        operands:
            - "false"
